# Memória
TOTAL_QUADROS_MEMORIA = 20
QUADROS_MEMORIA_TEMPO_REAL = 8
QUADROS_MEMORIA_USUARIO = 12
TAMANHO_QUADRO_KB = 1

# Escalonamento
PRIORIDADE_TEMPO_REAL = 0
MAX_PRIORIDADE_USUARIO = 3
QUANTUM_USUARIO = 1          # ms
MAX_PROCESSOS = 1000

# Recursos de E/S
TOTAL_SCANNERS = 1
TOTAL_IMPRESSORAS = 2
TOTAL_MODEMS = 1
TOTAL_DRIVES_SATA = 2

# Sistema de Arquivos
BLOCO_LIVRE = "0"
OPERACAO_CRIAR = 0
OPERACAO_DELETAR = 1

# Diretórios padrão
ARQUIVO_PROCESSOS_PADRAO = "Testes/CasosDeTeste/processes.txt"
ARQUIVO_SISTEMA_ARQUIVOS_PADRAO = "Testes/CasosDeTeste/files.txt"
ARQUIVO_REFERENCIAS_PADRAO = "Testes/CasosDeTeste/string.txt"

# Mensagens
ROTULO_DESPACHANTE = "dispatcher =>"
ROTULO_SISTEMA_ARQUIVOS = "Sistema de arquivos =>"
ROTULO_FALTAS_PAGINA = "Número de Faltas de Páginas por processo:"

# Modos de leitura do Parser de Entrada
HABILITAR_COMPATIBILIDADE_PDF = True